## Keras

In [ ]:
!pip install keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Define a simple Sequential model using standalone Keras
model = Sequential([
    Dense(10, activation='relu', input_shape=(4,)),  # Hidden layer
    Dense(5, activation='relu'),  # Hidden layer
    Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            55 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 111 (444.00 B)

 Trainable params: 111 (444.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow as tf

# Define a simple Sequential model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy')

# Print the model summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 61 (244.00 B)

 Trainable params: 61 (244.00 B)

 Non-trainable params: 0 (0.00 B)

## Tensorflow

In [ ]:
import tensorflow as tf

# Define tensors
a = tf.constant([1.0, 2.0])
b = tf.constant([3.0, 4.0])

# Perform basic operations
sum_result = tf.add(a, b)
dot_product = tf.tensordot(a, b, axes=1)

print(f"Sum: {sum_result}")
print(f"Dot Product: {dot_product}")


Sum: [4. 6.]
Dot Product: 11.0


In [ ]:
import tensorflow as tf

# Define a simple neural network using TensorFlow's low-level API
class SimpleNN(tf.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.w = tf.Variable(tf.random.normal([2, 2]), name="weight")  # Weight matrix
        self.b = tf.Variable(tf.zeros([2]), name="bias")  # Bias vector

    def __call__(self, x):
        return tf.nn.relu(tf.matmul(x, self.w) + self.b)  # ReLU activation

# Create a model and test it
model = SimpleNN()
input_data = tf.constant([[1.0, 2.0], [3.0, 4.0]])
output = model(input_data)

# Output result from model
print("Output:", output)

# Display trainable parameters
print("\nTrainable Parameters:")
print("Weights (w):")
print(model.w.numpy())  # Display weight matrix
print("Biases (b):")
print(model.b.numpy())  # Display bias vector


Output: tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)

Trainable Parameters:
Weights (w):
[[-2.7745976  -0.7701334 ]
 [-1.2969123  -0.08517349]]
Biases (b):
[0. 0.]


## Pytorch

In [ ]:
# Install PyTorch
!pip install torch

In [ ]:
import torch

# Define tensors
a = torch.tensor([2.0, 3.0])
b = torch.tensor([4.0, 5.0])

# Perform basic operations
sum_result = a + b
dot_product = torch.dot(a, b)

print(f"Sum: {sum_result}")
print(f"Dot Product: {dot_product}")


Sum: tensor([6., 8.])
Dot Product: 23.0


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(4, 8)  # Hidden layer
        self.fc2 = nn.Linear(8, 10)
        self.fc3 = nn.Linear(10, 1)  # Output layer

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Apply ReLU activation
        x = torch.sigmoid(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))  # Apply Sigmoid activation for output
        return x

# Instantiate the model
model = SimpleNN()

# Print the model architecture
print("Model architecture:")
print(model)

# Example input to test the model
input_data = torch.rand(1, 4)  # Batch size = 1, input features = 4
output = model(input_data)
print(f"\nOutput: {output}")

# Print trainable parameters (weights and biases)
print("\nTrainable Parameters:")
for name, param in model.named_parameters():
    print(f"{name}:\n{param.data}")


Model architecture:
SimpleNN(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=1, bias=True)
)

Output: tensor([[0.6298]], grad_fn=<SigmoidBackward0>)

Trainable Parameters:
fc1.weight:
tensor([[ 0.4969, -0.4374, -0.2892, -0.4972],
        [ 0.1805, -0.2314,  0.1972,  0.0403],
        [ 0.2837,  0.3289, -0.2258, -0.0444],
        [-0.1853,  0.2852, -0.2003,  0.1704],
        [ 0.3121, -0.4030,  0.2821, -0.4634],
        [-0.2787,  0.2443, -0.1889,  0.2796],
        [-0.0242, -0.2097,  0.0748, -0.4625],
        [-0.0246,  0.4287,  0.3391,  0.0012]])
fc1.bias:
tensor([ 0.3375, -0.4347,  0.0652, -0.4097, -0.1450,  0.1502, -0.3454, -0.3587])
fc2.weight:
tensor([[ 0.3015, -0.3487,  0.2609, -0.3085,  0.2786, -0.0212, -0.0930, -0.2404],
        [ 0.2947, -0.0648, -0.0965, -0.2599,  0.0442,  0.2184, -0.3052,  0.0117],
        [-0.1688,  0.1954, -0.1230,  0.2165,  0.3255,  0.1807,  0

## Experiments with IRIS Data with Keras

In [ ]:
import numpy as np
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

print(X)
print(y)


# One-hot encode the labels (since we have 3 classes)
encoder = OneHotEncoder(handle_unknown='ignore')
y = encoder.fit_transform(y.reshape(-1, 1))

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
# Define a simple neural network using Sigmoid activation in all layers
def build_model_sigmoid():
    model = Sequential([
        Dense(10, activation='sigmoid', input_shape=(4,)),  # Hidden layer with Sigmoid
        Dense(10, activation='sigmoid'),  # Another hidden layer with Sigmoid
        Dense(3, activation='softmax')  # Output layer with softmax for classification
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Build the model
model_sigmoid = build_model_sigmoid()

# Train the model
history_sigmoid = model_sigmoid.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), verbose=2)

# Evaluate the model
test_loss_sigmoid, test_acc_sigmoid = model_sigmoid.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy (All Sigmoid): {test_acc_sigmoid}")


Epoch 1/50


TypeError: Failed to convert elements of SparseTensor(indices=Tensor("data_1:0", shape=(None, 2), dtype=int64), values=Tensor("data_2:0", shape=(None,), dtype=float32), dense_shape=Tensor("data_3:0", shape=(2,), dtype=int64)) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.

In [ ]:
# Define a simple neural network using ReLU activation in all layers
def build_model_relu():
    model = Sequential([
        Dense(10, activation='relu', input_shape=(4,)),  # Hidden layer with ReLU
        Dense(10, activation='relu'),  # Another hidden layer with ReLU
        Dense(3, activation='softmax')  # Output layer with softmax for classification
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Build the model
model_relu = build_model_relu()

# Train the model
history_relu = model_relu.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), verbose=2)

# Evaluate the model
test_loss_relu, test_acc_relu = model_relu.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy (All ReLU): {test_acc_relu}")


In [ ]:
from tensorflow.keras.layers import LeakyReLU

# Define a simple neural network using Leaky ReLU activation in all layers
def build_model_leaky_relu():
    model = Sequential([
        Dense(10, input_shape=(4,)),  # First hidden layer without activation, add LeakyReLU separately
        LeakyReLU(alpha=0.01),  # Leaky ReLU activation with small slope for negative values
        Dense(10),  # Second hidden layer
        LeakyReLU(alpha=0.01),  # Leaky ReLU activation
        Dense(3, activation='softmax')  # Output layer with softmax for classification
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Build the model with Leaky ReLU
model_leaky_relu = build_model_leaky_relu()

# Train the model
history_leaky_relu = model_leaky_relu.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), verbose=2)

# Evaluate the model
test_loss_leaky_relu, test_acc_leaky_relu = model_leaky_relu.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy (Leaky ReLU): {test_acc_leaky_relu}")


In [ ]:
import matplotlib.pyplot as plt

# Plot training and validation accuracy
plt.plot(history_sigmoid.history['accuracy'], label='Sigmoid Accuracy')
plt.plot(history_relu.history['accuracy'], label='ReLU Accuracy')
plt.plot(history_leaky_relu.history['accuracy'], label='Leaky ReLU Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()
